export class CompanyInfo {
    email: string;
    cName: string;
    cPhone: number;
    // jSpec: String;
    location: String;
    jobs: Array<string>;  // Will hold keys to the jobs, the keys are auto generated by firebase.push
}